Repository flubshi/pvr.waipu, pull requests merged in 2019-11, with the labels that each got.

#39 [debian] fix dependencies after 316c1a6
  debian/control
Labels: Type: Fix, v19 Matrix

#42 Fix Debian: Set rapidjson dependency >=1.1.0
  CMakeLists.txt
  FindRapidJSON.cmake
  debian/control
Labels: Type: Fix, v19 Matrix

#43 Implement O2 authentication
  pvr.waipu/addon.xml.in
  pvr.waipu/resources/language/resource.language.de_de/strings.po
  pvr.waipu/resources/language/resource.language.en_gb/strings.po
  pvr.waipu/resources/settings.xml
  src/Utils.cpp
  src/Utils.h
  src/WaipuData.cpp
  src/WaipuData.h
  src/client.cpp
  src/client.h
Labels: Type: Feature, v19 Matrix

#49 Leia channel unique id
  pvr.waipu/addon.xml.in
  src/Utils.cpp
  src/Utils.h
  src/WaipuData.cpp
  src/WaipuData.h
Labels: Type: Fix, v18 Leia

#48 Matrix: Implement channel groups
  pvr.waipu/addon.xml.in
  src/Utils.cpp
  src/Utils.h
  src/WaipuData.cpp
  src/WaipuData.h
  src/client.cpp
Labels: Type: Feature, v19 Matrix
