Repository flubshi/pvr.waipu, pull requests merged in 2021-10, with the labels that each got.

#158 Translated using Weblate (backport)
  pvr.waipu/resources/language/resource.language.af_za/strings.po
  pvr.waipu/resources/language/resource.language.am_et/strings.po
  pvr.waipu/resources/language/resource.language.ar_sa/strings.po
  pvr.waipu/resources/language/resource.language.bg_bg/strings.po
  pvr.waipu/resources/language/resource.language.da_dk/strings.po
  pvr.waipu/resources/language/resource.language.de_de/strings.po
  pvr.waipu/resources/language/resource.language.et_ee/strings.po
  pvr.waipu/resources/language/resource.language.ko_kr/strings.po
Labels: v19 Matrix, Type: Backport

#159 Version 19.0.1
  pvr.waipu/addon.xml.in
Labels: v19 Matrix

#156 Version 20.0.1
  pvr.waipu/addon.xml.in
Labels: v20 Nexus

#154 [Nexus] Add supports recordings delete capability for PVR API 8.0.0
  pvr.waipu/addon.xml.in
  src/WaipuData.cpp
Labels: PVR API change
